### ISSUE TITLE
USER STORY: View Home page

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#1]
As a **Site Visitor** I can **view the Home page once the link has loaded** so that **I can understand the site purpose and use**

### Acceptance Criteria

- [x] Once the link has loaded, the Home page is visible
- [x] Clear navigation, the header and footer are present
- [x] The page content shows the site purpose

### Tasks

- [x] Create base template and home template
- [x] Style header, footer and navigation bar
- [x] Add hero image and short description of site purpose
