### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#16]
As a **Registered User** I can **delete my comment** so that **I can control my engagement on the platform**

### Acceptance Criteria

- [x] 'Delete' button under the comment available only to the owner of the comment
- [x] Once clicked, the modal pop-up is asking for confirmation of deletion
- [x] Once confirmed, the comment is deleted from the database and is not visible on the site anymore

### Tasks

- [x] Implement an "Delete" button that is accessible to authenticated authors of comments, allowing them to delete their comments, accompanied by a confirmation modal to prevent accidental deletion
- [x] Add message to confirm successful comment deletion
