### ISSUE TITLE
USER STORY: Create a recipe/article

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#18]
As a **Registered User** I can **create a post** so that **I can share my knowledge and experience or research outcome**

### Acceptance Criteria

- [x] Navigation item to add a new post
- [x] Once clicked, a form is available to fill out all the necessary info
- [x] After submitting, the post is waiting for approval

### Tasks

- [x] Create view and form 
- [x] Add working link to the nav bar
- [x] Test the form, add few new posts
