### ISSUE TITLE
USER STORY: View latest posts on home page

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#2]
As a **Site Visitor** I can **find 3 latest  posts on Home page** so that **I can read them**

### Acceptance Criteria

- [x] Section called "Latest posts"
- [x] Includes 3 posts matching the criteria
- [x] Can click on any of them to view the full post

### Tasks

- [x] Create PostDetail view template
- [x] Add section "latests posts" to home template, render the existing posts
- [x] Test each post view by opening them
