### ISSUE TITLE
USER STORY: Fill out / Update profile info

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#25]
As a **Registered User** I can **fill out the profile information** so that **other users can get to know me better**

### Acceptance Criteria

- [x] Button to 'edit' profile info, available only to the owner of the profile
- [x] Once clicked, the form is available to update prefilled info
- [x] After submitting, the updated info is visible in the profile

### Tasks

- [x] Create form to update the profile
- [x] Insert the edit button on the profile page
- [x] Test out the functionality, ensure that only the owner of the profile can update it
