### ISSUE TITLE
USER STORY: View my posts in my profile

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#28]
As a **Registered User** I can **click on my profile** so that **I can see all my posts** 

### Acceptance Criteria

- [x] When clicked on profile, the profile opens
- [x] There's a section with all posts of the user displayed

### Tasks

- [x] Create user profile page and view
- [x] Add link to the nav bar
- [x] Get the posts from the database and display under the profile
- [x] Add small messages to differentiate drafts from published posts, note the posts waiting for approval
