### ISSUE TITLE
USER STORY: View blog posts (paginated)

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#3]
As a **Site Visitor** I can **click on Blog nav item** so that **I can view posts (articles) to choose what to read**

### Acceptance Criteria

- [x] Nav item called Blog
- [x] Includes paginated list of all posts
- [x] When click on any of them, you can read the article 

### Tasks

- [x] Create Blog page
- [x] Display published posts from the database
- [x] Implement pagination by 6 posts on each page
