### ISSUE TITLE
USER STORY: Manage posts in admin panel

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#31]
As a **Site Admin** I can **manage posts in the admin panel** so that **I can enrich the content, correct mistakes, remove incorrect or outdated posts**

### Acceptance Criteria

- [x] Admin has access to admin panel and is logged in
- [x] The posts section is available
- [x] The posts can be created, updated and deleted if necessary
- [x] The post can be approved by admin for publishing

### Tasks

- [x] Create superuser
- [x] Create Post model
- [x] Set up admin panel to inclide the posts
- [x] Test CRUD functionality in admin panel
- [x] Approve several new posts
