### ISSUE TITLE
USER STORY: Agile Methodology

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#36]
As a **developer** I can **use Agile** so that **I can deliver high quality product that meets the user needs**

### Acceptance Criteria

- [x] Understand the core principles and values of Agile methodology
- [x] Effectively use Agile practices such as user stories, iterations, epics

### Tasks

- [x] Establish a backlog of user stories that capture the requirements and priorities of the project
- [x] Break down user stories into smaller, manageable tasks that can be completed
- [x] Conduct iteration planning to determine which user stories and tasks will be included
