### ISSUE TITLE
USER STORY: Design Database Schema

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#37]
As a **developer** I can **plan a database schema** so that **I can effectively store and manage blog data, ensuring optimal perfomance and flexibility**

### Acceptance Criteria

- [x] The database schema containing all neccessary tables

### Tasks

- [x] Design table for posts
- [x] Design table for comments
- [x] Design table for profile
