### ISSUE TITLE
USER STORY: Create wireframes

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#38]
As a **developer** I can **create wireframes** so that **I can represent the layout and structure of the site**

### Acceptance Criteria

- [ ] Wireframes should include key components such as navigation menus, content sections, and interactive elements
- [ ] Wireframes should reflect the user flow and interactions within the application

### Tasks

- [ ]  Create detailed wireframes using Balsamiq
