### ISSUE TITLE
USER STORY: Design

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#39]
As a **developer** I can **create visually engaging and responsive design** so that **users can easily navigate the site and access relevant information**

### Acceptance Criteria

- [x] Design should be responsive and optimized for different devices and screen sizes
- [x] Consistent colors, typography, and spacing should be maintained throughout the project
- [x] Design should enhance user experience and usability, focusing on intuitive navigation and clear information hierarchy

### Tasks

- [x] Ensure design is visually engaging and accessible
- [x] Demonstrate design solutions in Wireframes including responsive design principles to ensure a seamless user experience
- [x] Document design solutions in README.md
