### ISSUE TITLE
USER STORY: Create Django Project

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#40]
As a **developer** I can **install and add basic configurations to Django** so that **I can create a working app**

### Acceptance Criteria

- [x] A repository for the new project is created
- [x] Django is installed into the workspace
- [x] A new Django project is created with the necessary files and directories
- [x] The Django development server runs without any errors 
- [x] The Django project structure follows best practices.

### Tasks
- [x] Install Django 
- [x] Create new project 
- [x] Create app 
- [x] Install packages
- [x] Set up settings.py
