### ISSUE TITLE
USER STORY: Performance and Accessibility Testing

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#44]
As a **developer** I can **ensure that application meets performance and accessibility standards** so that **it provides a seamless experience for all users and performs optimally**

### Acceptance Criteria

- [ ] Page load times should be measured and documented using tool Lighthouse
- [ ] Accessibility audits should be conducted using tools Wave or Lighthouse
- [ ] Results and if any issues identified included in README.md

### Tasks

- [ ] Set up accessibility testing tools and environment Wave, to evaluate the accessibility of the application
- [ ] Document accessibility testing results
- [ ] Set up performance testing tools and environment Lighthouse to evaluate page load times and performance metrics
- [ ] Document performance testing results
