### ISSUE TITLE
USER STORY: Sign Up feature

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#5]
As a **Site Visitor** I can **sign up** so that **I can get access Registered User’s features**

### Acceptance Criteria

- [x] Sign Up page with a form
- [x] The site is displaying that the user is not logged in yet
- [x] Upon successful registration, users view a confirmation message
- [x] The user is able to successfully log in

### Tasks

- [x] Create a registration form with fields for username, email, and password
- [x] Implement backend validation for user input
- [x] Set up a confirmation message display upon successful registration
