### ISSUE TITLE
USER STORY: Login and Logout Features

### ISSUE THREAD

**Issue by VL-ocean** [VL-ocean/coffee-choco-prj#6]
As a **Registered User** I can **log in using my username and password** so that **I can be authenticated in the system and use its features**

### Acceptance Criteria

- [x] Login page with the form
- [x] After entering the username and password correctly, the user logs in successfully
- [x] The site is displaying the notification that the user is now logged in
- [x] Display option to log out.
- [x] Display confirmation when logged out

### Tasks

- [x] Implement backend authentication for user login
- [x] Verify user credentials and allow access upon successful login
- [x] Set up confirmation when successfully logged in
- [x] Set up confirmation of successful log out
